#include "main.h"

/* Define external variables */
ADC_HandleTypeDef hadc;
UART_HandleTypeDef huart2;

int main(void) {
    /* Initialize the HAL Library */
    HAL_Init();

    /* Configure the system clock */
    SystemClock_Config();

    /* Initialize all configured peripherals */
    MX_GPIO_Init();
    MX_ADC_Init();
    MX_USART2_UART_Init();

    /* Start ADC Calibration (if necessary) */
    // HAL_ADCEx_Calibration_Start(&hadc, ADC_SINGLE_ENDED);

    /* Infinite loop */
    while (1) {
        float temperature = Read_Temperature();
        
        if (temperature != -1.0f) {
            printf("Temperature: %.2f C\r\n", temperature);
        } else {
            printf("Temperature read error\r\n");
        }
        
        HAL_Delay(1000); // Wait for 1 second
    }
}

/* Implement other functions here */
void SystemClock_Config(void) {
    /* Implementation of system clock configuration */
    // This function is typically auto-generated by STM32CubeMX or PlatformIO
}

void MX_GPIO_Init(void) {
    /* Implementation of GPIO initialization */
    // This function is typically auto-generated by STM32CubeMX or PlatformIO
}

void MX_ADC_Init(void) {
    /* Implementation of ADC initialization */
    // This function is typically auto-generated by STM32CubeMX or PlatformIO
}

void MX_USART2_UART_Init(void) {
    /* Implementation of USART2 initialization */
    // This function is typically auto-generated by STM32CubeMX or PlatformIO
}

float Read_Temperature(void) {
    /* Implementation of temperature reading */
    HAL_ADC_Start(&hadc);
    
    if(HAL_ADC_PollForConversion(&hadc, 1000000) == HAL_OK) {
        uint32_t adcValue = HAL_ADC_GetValue(&hadc);
        float voltage = (adcValue * 3.3f) / 4095.0f;
        float temperature = voltage * 100.0f; // LM35 scale factor (10mV per degree Celsius)
        return temperature;
    } else {
        // Handle timeout or error
        return -1.0f;
    }
}
