/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <stdio.h>

/* Private variables ---------------------------------------------------------*/
ADC_HandleTypeDef hadc1;

/* Function Prototypes -------------------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
float Read_Temperature(void);

int main(void)
{
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_ADC1_Init();

  /* Start ADC Calibration */
  HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED);

  /* Infinite loop */
  while (1)
  {
    float temperature = Read_Temperature();
    
    // For demonstration, you might send this value over UART or toggle LEDs
    // Here, we'll just add a delay
    HAL_Delay(1000); // Wait for 1 second
  }
}

/**
  * @brief  Reads the temperature from LM35 sensor.
  * @retval Temperature in Celsius.
  */
float Read_Temperature(void)
{
  HAL_ADC_Start(&hadc1);
  
  // Wait for conversion to complete
  if(HAL_ADC_PollForConversion(&hadc1, 1000000) == HAL_OK)
  {
    uint32_t adcValue = HAL_ADC_GetValue(&hadc1);
    // Assuming Vref = 3.3V and 12-bit ADC
    float voltage = (adcValue * 3.3f) / 4095.0f;
    float temperature = voltage * 100.0f; // LM35 scale factor (10mV per degree Celsius)
    return temperature;
  }
  else
  {
    // Handle timeout or error
    return -1.0f;
  }
}

/* ADC1 init function */
static void MX_ADC1_Init(void)
{
  ADC_ChannelConfTypeDef sConfig = {0};

  /** Common config
  */
  hadc1.Instance = ADC1;
  hadc1.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc1.Init.ContinuousConvMode = DISABLE;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
  hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc1.Init.NbrOfConversion = 1;
  if (HAL_ADC_Init(&hadc1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_0; // PA0
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_15CYCLES;
  if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
}

/* GPIO init function */
static void MX_GPIO_Init(void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE();
  // Initialize other GPIOs if necessary
}

/* System Clock Configuration */
void SystemClock_Config(void)
{
  // Configure the system clock as per your hardware setup
  // This is usually auto-generated by STM32CubeMX
}

/* Error Handler */
void Error_Handler(void)
{
  // Stay here
  while(1) {}
}

#ifdef  USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{ 
  // Report the name of the source file and the source line number
}
#endif /* USE_FULL_ASSERT */
